package com.google.mediapipe.tasks.vision.provider;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import org.gradle.api.DefaultTask;
import org.gradle.api.NamedDomainObjectContainer;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.util.List;

public abstract class GenerateVisionProviderTask extends DefaultTask {
    private static final String PACKAGE_NAME = "com.mediapipe.tasks.vision.provider";

    @Input
    public abstract Property<NamedDomainObjectContainer<VisionTask>> getTasksConfiguration();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDir();

    @TaskAction
    public void generate() throws IOException {
        String basePackage = PACKAGE_NAME;
        ClassName visionProviderClassName = ClassName.get(basePackage, "VisionProvider");

        // Define common ClassNames for easier reference
        ClassName contextCn = ClassName.get("android.content", "Context");
        ClassName nonNullCn = ClassName.get("androidx.annotation", "NonNull");
        ClassName futureCn = ClassName.get("java.util.concurrent", "Future");
        ClassName listCn = ClassName.get("java.util", "List");
        ClassName setCn = ClassName.get("java.util", "Set");
        ClassName stringCn = ClassName.get(String.class);
        ClassName visionModelCn = ClassName.get(basePackage, "VisionModel");
        ClassName visionProviderBaseCn = ClassName.get(basePackage, "VisionProviderBase");
        ClassName quantizationCn = ClassName.get("com.mediapipe.tasks.core", "Quantization");
        ClassName runningModeCn = ClassName.get("com.google.mediapipe.tasks.vision.core", "RunningMode");
        ClassName classifierOptionsCn = ClassName.get("com.google.mediapipe.tasks.components.processors", "ClassifierOptions");

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder("VisionProvider")
                .addModifiers(Modifier.PUBLIC)
                .superclass(visionProviderBaseCn)
                .addJavadoc("Generated by the VisionProvider Gradle Plugin. Do not edit.");

        // --- Constructor and Static Creator ---
        classBuilder.addMethod(
                MethodSpec.constructorBuilder()
                        .addParameter(contextCn, "context")
                        .addStatement("super(context)")
                        .build()
        );
        classBuilder.addMethod(
                MethodSpec.methodBuilder("create")
                        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                        .addAnnotation(nonNullCn)
                        .addParameter(ParameterSpec.builder(contextCn, "context").addAnnotation(nonNullCn).build())
                        .returns(visionProviderClassName)
                        .addStatement("return new $T(context)", visionProviderClassName)
                        .build()
        );

        // --- Generate sections for each task from the Gradle configuration ---
        NamedDomainObjectContainer<VisionTask> tasks = getTasksConfiguration().get();

        generateModels(classBuilder, tasks, visionModelCn, quantizationCn);
        generateSettings(classBuilder, tasks, runningModeCn, listCn, setCn, stringCn, nonNullCn, classifierOptionsCn);
        generateCreators(classBuilder, tasks, futureCn, nonNullCn);

        // --- Write the generated class to a file ---
        JavaFile javaFile = JavaFile.builder(basePackage, classBuilder.build())
                .indent("    ")
                .build();

        getOutputDir().get().getAsFile().mkdirs();
        javaFile.writeTo(getOutputDir().get().getAsFile());
    }

    private void generateModels(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            TypeName visionModelCn,
            ClassName quantizationCn
    ) {
        for (VisionTask task : tasks) {
            TypeSpec.Builder modelEnumBuilder = TypeSpec.enumBuilder(task.getName() + "Model")
                    .addModifiers(Modifier.PUBLIC)
                    .addSuperinterface(visionModelCn);

            modelEnumBuilder.addField(String.class, "modelName", Modifier.PRIVATE, Modifier.FINAL);
            modelEnumBuilder.addField(String.class, "version", Modifier.PRIVATE, Modifier.FINAL);
            modelEnumBuilder.addField(quantizationCn, "quantization", Modifier.PRIVATE, Modifier.FINAL);

            modelEnumBuilder.addMethod(
                    MethodSpec.constructorBuilder()
                            .addParameter(String.class, "modelName")
                            .addParameter(String.class, "version")
                            .addParameter(quantizationCn, "quantization")
                            .addStatement("this.modelName = modelName")
                            .addStatement("this.version = version")
                            .addStatement("this.quantization = quantization")
                            .build()
            );

            task.getModels().get().forEach(model ->
                    modelEnumBuilder.addEnumConstant(
                            model.getEnumName(),
                            TypeSpec.anonymousClassBuilder(
                                    "$S, $S, $T.$L",
                                    model.getModelName(),
                                    model.getVersion(),
                                    quantizationCn,
                                    model.getQuantization()
                            ).build()
                    )
            );

            modelEnumBuilder.addMethod(createGetter("getModelName", ClassName.get(String.class), "modelName"));
            modelEnumBuilder.addMethod(createGetter("getVersion", ClassName.get(String.class), "version"));
            modelEnumBuilder.addMethod(createGetter("getQuantization", quantizationCn, "quantization"));

            classBuilder.addType(modelEnumBuilder.build());
        }
    }

    private void generateSettings(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName runningModeCn,
            ClassName listCn,
            ClassName setCn,
            ClassName stringCn,
            ClassName nonNullCn,
            ClassName classifierOptionsCn
    ) {
        ParameterizedTypeName stringListType = ParameterizedTypeName.get(listCn, stringCn);
        ParameterizedTypeName stringSetType = ParameterizedTypeName.get(setCn, stringCn);
        ClassName visionProviderBaseCn = ClassName.get(PACKAGE_NAME, "VisionProviderBase");

        for (VisionTask task : tasks) {
            String taskName = task.getName();
            if (taskName.equals("FaceStylizer")) continue;

            ClassName recordClassName = ClassName.get("", taskName + "Settings");
            TypeSpec.Builder recordBuilder = TypeSpec.recordBuilder(recordClassName)
                    .addModifiers(Modifier.PUBLIC);

            List<FieldSpec> fields;
            MethodSpec.Builder defaultConstructor = MethodSpec.constructorBuilder().addModifiers(Modifier.PUBLIC);

            switch (taskName) {
                case "FaceDetector":
                    fields = List.of(
                            FieldSpec.builder(TypeName.FLOAT, "minDetectionConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minSuppressionThreshold").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "FaceLandmarker":
                    fields = List.of(
                            FieldSpec.builder(TypeName.FLOAT, "minFaceDetectionConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minFacePresenceConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minTrackingConfidence").build(),
                            FieldSpec.builder(TypeName.INT, "numFaces").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "outputFaceBlendshapes").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "outputFacialTransformationMatrixes").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_NUM_RESULTS, $T.DEFAULT_OUTPUT_BLENDSHAPES, $T.DEFAULT_OUTPUT_FACIAL_TRANSFORMATION_MATRIXES, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "GestureRecognizer":
                    fields = List.of(
                            FieldSpec.builder(TypeName.FLOAT, "minHandDetectionConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minHandPresenceConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minTrackingConfidence").build(),
                            FieldSpec.builder(TypeName.INT, "numHands").build(),
                            FieldSpec.builder(classifierOptionsCn, "cannedGesturesClassifierOptions").build(),
                            FieldSpec.builder(classifierOptionsCn, "customGesturesClassifierOptions").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_NUM_RESULTS, $T.DEFAULT_CLASSIFIER_OPTIONS, $T.DEFAULT_CLASSIFIER_OPTIONS, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "HandLandmarker":
                    fields = List.of(
                            FieldSpec.builder(TypeName.FLOAT, "minHandDetectionConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minHandPresenceConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minTrackingConfidence").build(),
                            FieldSpec.builder(TypeName.INT, "numHands").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_NUM_RESULTS, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "ImageClassifier":
                case "ObjectDetector":
                    fields = List.of(
                            FieldSpec.builder(stringCn, "displayNamesLocale").build(),
                            FieldSpec.builder(TypeName.INT, "maxResults").build(),
                            FieldSpec.builder(TypeName.FLOAT, "scoreThreshold").build(),
                            FieldSpec.builder(stringSetType, "categoryAllowlist").build(),
                            FieldSpec.builder(stringSetType, "categoryDenylist").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    float scoreThreshold = taskName.equals("ImageClassifier") ? 0.0f : 0.5f; // ImageClassifier has a different default
                    defaultConstructor.addStatement("this($T.DEFAULT_DISPLAY_NAMES_LOCALE, $T.UNLIMITED_RESULTS, $L, $T.DEFAULT_CATEGORY_LIST, $T.DEFAULT_CATEGORY_LIST, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, scoreThreshold, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "ImageEmbedder":
                    fields = List.of(
                            FieldSpec.builder(TypeName.BOOLEAN, "l2Normalize").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "quantize").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_L2_NORMALIZE, $T.DEFAULT_QUANTIZE, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "PoseLandmarker":
                    fields = List.of(
                            FieldSpec.builder(TypeName.FLOAT, "minPoseDetectionConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minPosePresenceConfidence").build(),
                            FieldSpec.builder(TypeName.FLOAT, "minTrackingConfidence").build(),
                            FieldSpec.builder(TypeName.INT, "numPoses").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "outputSegmentationMasks").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_CONFIDENCE, $T.DEFAULT_NUM_RESULTS, $T.DEFAULT_OUTPUT_SEGMENTATION_MASKS, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "InteractiveSegmenter":
                    fields = List.of(
                            FieldSpec.builder(TypeName.BOOLEAN, "outputConfidenceMasks").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "outputCategoryMask").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_OUTPUT_CONFIDENCE_MASKS, $T.DEFAULT_OUTPUT_CATEGORY_MASK, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                case "ImageSegmenter":
                    fields = List.of(
                            FieldSpec.builder(TypeName.BOOLEAN, "outputConfidenceMasks").build(),
                            FieldSpec.builder(TypeName.BOOLEAN, "outputCategoryMask").build(),
                            FieldSpec.builder(stringCn, "displayNamesLocale").build(),
                            FieldSpec.builder(runningModeCn, "runningMode").addAnnotation(nonNullCn).build()
                    );
                    defaultConstructor.addStatement("this($T.DEFAULT_OUTPUT_CONFIDENCE_MASKS, $T.DEFAULT_OUTPUT_CATEGORY_MASK, $T.DEFAULT_DISPLAY_NAMES_LOCALE, $T.DEFAULT_RUNNING_MODE)",
                            visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn, visionProviderBaseCn);
                    break;
                default:
                    // Skip or throw an error for unhandled tasks
                    continue;
            }

            // Add all defined fields to the record
            recordBuilder.addFields(fields);

            // Add the default (no-arg) constructor
            recordBuilder.addMethod(defaultConstructor.build());

            // Generate and add a 'withX' method for each field
            List<String> allFieldNames = fields.stream().map(f -> f.name()).toList();
            for (FieldSpec field : fields) {
                recordBuilder.addMethod(createWithMethod(recordClassName, field, allFieldNames));
            }

            classBuilder.addType(recordBuilder.build());
        }
    }

    private MethodSpec createWithMethod(ClassName recordClassName, FieldSpec targetField, List<String> allFieldNames) {
        String methodName = "with" + targetField.name().substring(0, 1).toUpperCase() + targetField.name().substring(1);

        // Create the parameter list for the 'new' call inside the method body
        String constructorParams = allFieldNames.stream()
                .map(fieldName -> fieldName.equals(targetField.name()) ? fieldName : "this." + fieldName)
                .collect(java.util.stream.Collectors.joining(", "));

        return MethodSpec.methodBuilder(methodName)
                .addModifiers(Modifier.PUBLIC)
                .returns(recordClassName)
                .addParameter(targetField.type(), targetField.name())
                .addStatement("return new $T(" + constructorParams + ")", recordClassName)
                .build();
    }
    private void generateCreators(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName futureCn,
            ClassName nonNullCn
    ) {
        for (VisionTask task : tasks) {
            String taskName = task.getName();
            if (taskName.equals("FaceStylizer")) continue;

            ClassName modelEnumCn = ClassName.get("", taskName + "Model");
            ClassName settingsRecordCn = ClassName.get("", taskName + "Settings");
            ClassName internalSettingsCn = ClassName.get("", taskName + "SettingsInternal");
            ClassName taskReturnCn = ClassName.get("com.google.mediapipe.tasks.vision." + taskName.toLowerCase(), taskName);
            ParameterizedTypeName futureOfTask = ParameterizedTypeName.get(futureCn, taskReturnCn);
            String defaultModel = task.getDefaultModel().get();

            classBuilder.addMethod(
                    MethodSpec.methodBuilder("create" + taskName)
                            .addModifiers(Modifier.PUBLIC)
                            .returns(futureOfTask)
                            .addStatement("return create" + taskName + "Impl($T.$L, new $T())",
                                    modelEnumCn, defaultModel, internalSettingsCn)
                            .build()
            );

            classBuilder.addMethod(
                    MethodSpec.methodBuilder("create" + taskName)
                            .addModifiers(Modifier.PUBLIC)
                            .addParameter(ParameterSpec.builder(modelEnumCn, "model").addAnnotation(nonNullCn).build())
                            .returns(futureOfTask)
                            .addStatement("return create" + taskName + "Impl(model, new $T())", internalSettingsCn)
                            .build()
            );

            String settingsParams = switch (taskName) {
                case "FaceDetector" ->
                        "settings.minDetectionConfidence(), settings.minSuppressionThreshold(), settings.runningMode()";
                case "FaceLandmarker" ->
                        "settings.minFaceDetectionConfidence(), settings.minFacePresenceConfidence(), settings.minTrackingConfidence(), settings.numFaces(), settings.outputFaceBlendshapes(), settings.outputFacialTransformationMatrixes(), settings.runningMode()";
                case "GestureRecognizer" ->
                        "settings.minHandDetectionConfidence(), settings.minHandPresenceConfidence(), settings.minTrackingConfidence(), settings.numHands(), settings.cannedGesturesClassifierOptions(), settings.customGesturesClassifierOptions(), settings.runningMode()";
                case "HandLandmarker" ->
                        "settings.minHandDetectionConfidence(), settings.minHandPresenceConfidence(), settings.minTrackingConfidence(), settings.numHands(), settings.runningMode()";
                case "ImageClassifier", "ObjectDetector" ->
                        "settings.displayNamesLocale(), settings.maxResults(), settings.scoreThreshold(), settings.categoryAllowlist(), settings.categoryDenylist(), settings.runningMode()";
                case "ImageEmbedder" ->
                        "settings.l2Normalize(), settings.quantize(), settings.runningMode()";
                case "PoseLandmarker" ->
                        "settings.minPoseDetectionConfidence(), settings.minPosePresenceConfidence(), settings.minTrackingConfidence(), settings.numPoses(), settings.outputSegmentationMasks(), settings.runningMode()";
                case "InteractiveSegmenter" ->
                        "settings.outputConfidenceMasks(), settings.outputCategoryMask(), settings.runningMode()";
                case "ImageSegmenter" ->
                        "settings.outputConfidenceMasks(), settings.outputCategoryMask(), settings.displayNamesLocale(), settings.runningMode()";
                default -> "";
            };

            classBuilder.addMethod(
                    MethodSpec.methodBuilder("create" + taskName)
                            .addModifiers(Modifier.PUBLIC)
                            .addParameter(ParameterSpec.builder(modelEnumCn, "model").addAnnotation(nonNullCn).build())
                            .addParameter(ParameterSpec.builder(settingsRecordCn, "settings").addAnnotation(nonNullCn).build())
                            .returns(futureOfTask)
                            .addStatement("return create" + taskName + "Impl(model, new $T(" + settingsParams + "))", internalSettingsCn)
                            .build()
            );
        }
    }

    private MethodSpec createGetter(String name, TypeName returnType, String field) {
        return MethodSpec.methodBuilder(name)
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(returnType)
                .addStatement("return this.$L", field)
                .build();
    }
}