package com.google.mediapipe.tasks.vision.provider;

import com.squareup.kotlinpoet.ClassName;
import com.squareup.kotlinpoet.CodeBlock;
import com.squareup.kotlinpoet.FileSpec;
import com.squareup.kotlinpoet.FunSpec;
import com.squareup.kotlinpoet.KModifier;
import com.squareup.kotlinpoet.ParameterSpec;
import com.squareup.kotlinpoet.ParameterizedTypeName;
import com.squareup.kotlinpoet.PropertySpec;
import com.squareup.kotlinpoet.TypeName;
import com.squareup.kotlinpoet.TypeSpec;
import org.gradle.api.DefaultTask;
import org.gradle.api.NamedDomainObjectContainer;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.model.ObjectFactory;
import org.gradle.api.tasks.Nested;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import javax.inject.Inject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import kotlin.jvm.JvmOverloads;
import kotlin.jvm.JvmStatic;

public abstract class GenerateVisionProviderTask extends DefaultTask {
    private static final String PACKAGE_NAME = "com.google.mediapipe.tasks.vision.provider";
    private final NamedDomainObjectContainer<VisionTask> tasksConfiguration;

    @OutputDirectory
    public abstract DirectoryProperty getOutputDir();

    @Inject
    public GenerateVisionProviderTask(ObjectFactory objectFactory) {
        this.tasksConfiguration = objectFactory.domainObjectContainer(VisionTask.class);
    }

    @Nested
    public NamedDomainObjectContainer<VisionTask> getTasksConfiguration() {
        return tasksConfiguration;
    }

    @TaskAction
    public void generate() throws IOException {
        FileSpec.Builder fileBuilder = FileSpec.builder(PACKAGE_NAME, "VisionProvider");
        ClassName visionProviderClassName = new ClassName(PACKAGE_NAME, "VisionProvider");

        ClassName contextCn = new ClassName("android.content", "Context");
        ClassName futureCn = new ClassName("java.util.concurrent", "Future");
        ClassName visionModelCn = new ClassName(PACKAGE_NAME, "VisionModel");
        ClassName visionProviderBaseCn = new ClassName(PACKAGE_NAME, "VisionProviderBase");
        ClassName quantizationCn = new ClassName("com.google.mediapipe.tasks.core", "Quantization");
        ClassName runningModeCn = new ClassName("com.google.mediapipe.tasks.vision.core", "RunningMode");
        ClassName classifierOptionsCn = new ClassName("com.google.mediapipe.tasks.components.processors", "ClassifierOptions");
        ClassName nonNullCn = new ClassName("androidx.annotation", "NonNull");

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder("VisionProvider")
                .addModifiers(KModifier.PUBLIC)
                .superclass(visionProviderBaseCn)
                .addKdoc("Generated by the VisionProvider Gradle Plugin. Do not edit.");

        classBuilder.primaryConstructor(
                FunSpec.constructorBuilder()
                        .addParameter("context", contextCn)
                        .build()
        );
        classBuilder.addSuperclassConstructorParameter("context");

        TypeSpec.Builder companionBuilder = TypeSpec.companionObjectBuilder()
                .addFunction(
                        FunSpec.builder("create")
                                .addAnnotation(JvmStatic.class)
                                .addParameter(ParameterSpec.builder("context", contextCn).addAnnotation(nonNullCn).build())
                                .returns(visionProviderClassName)
                                .addStatement("return %T(context)", visionProviderClassName)
                                .build()
                );
        classBuilder.addType(companionBuilder.build());

        NamedDomainObjectContainer<VisionTask> tasks = getTasksConfiguration();
        generateModels(classBuilder, tasks, visionModelCn, quantizationCn);
        generateSettings(classBuilder, tasks, runningModeCn, classifierOptionsCn);
        generateCreators(classBuilder, tasks, futureCn, nonNullCn);

        fileBuilder.addType(classBuilder.build());
        FileSpec fileSpec = fileBuilder.build();

        System.err.println("Output dir: " + getOutputDir().get().getAsFile());
        getOutputDir().get().getAsFile().mkdirs();
        fileSpec.writeTo(getOutputDir().get().getAsFile());
    }

    private void generateSettings(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName runningModeCn,
            ClassName classifierOptionsCn
    ) {
        ClassName visionProviderBaseCn = new ClassName(PACKAGE_NAME, "VisionProviderBase");
        ParameterizedTypeName stringListType = ParameterizedTypeName.get(new ClassName("kotlin.collections", "List"), new ClassName("kotlin", "String"));

        // Define common listener and type ClassNames
        ClassName errorListenerCn = new ClassName("com.google.mediapipe.tasks.core", "ErrorListener");
        ClassName resultListenerBaseCn = new ClassName("com.google.mediapipe.tasks.core", "OutputHandler", "ResultListener");

        for (VisionTask task : tasks) {
            String taskName = task.getName();
            if (taskName.equals("FaceStylizer")) continue;

            ClassName settingsClassName = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Settings");
            TypeSpec.Builder dataClassBuilder = TypeSpec.classBuilder(settingsClassName)
                    .addModifiers(KModifier.PUBLIC, KModifier.DATA);

            FunSpec.Builder constructorBuilder = FunSpec.constructorBuilder();
            List<ParameterSpec.Builder> taskSpecificParamBuilders;

            switch (taskName) {
                case "FaceDetector":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("minDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minSuppressionThreshold", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "FaceLandmarker":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("minFaceDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minFacePresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("numFaces", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("outputFaceBlendshapes", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_BLENDSHAPES", visionProviderBaseCn),
                            ParameterSpec.builder("outputFacialTransformationMatrixes", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_FACIAL_TRANSFORMATION_MATRIXES", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "GestureRecognizer":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("minHandDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minHandPresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("numHands", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("cannedGesturesClassifierOptions", classifierOptionsCn.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("customGesturesClassifierOptions", classifierOptionsCn.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "HandLandmarker":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("minHandDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minHandPresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("numHands", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "ImageClassifier":
                case "ObjectDetector":
                    float scoreThreshold = taskName.equals("ImageClassifier") ? 0.0f : 0.5f;
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("displayNamesLocale",KOTLIN_STRING_CN).defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                            ParameterSpec.builder("maxResults", Integer.TYPE).defaultValue("%T.UNLIMITED_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("scoreThreshold", Float.TYPE).defaultValue("%Lf", scoreThreshold),
                            // FIX: Use the list type here
                            ParameterSpec.builder("categoryAllowlist", stringListType.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("categoryDenylist", stringListType.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "ImageEmbedder":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("l2Normalize", Boolean.TYPE).defaultValue("%T.DEFAULT_L2_NORMALIZE", visionProviderBaseCn),
                            ParameterSpec.builder("quantize", Boolean.TYPE).defaultValue("%T.DEFAULT_QUANTIZE", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "PoseLandmarker":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("minPoseDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minPosePresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                            ParameterSpec.builder("numPoses", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("outputSegmentationMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_SEGMENTATION_MASKS", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "InteractiveSegmenter":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("outputConfidenceMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                            ParameterSpec.builder("outputCategoryMask", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                case "ImageSegmenter":
                    taskSpecificParamBuilders = List.of(
                            ParameterSpec.builder("outputConfidenceMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                            ParameterSpec.builder("outputCategoryMask", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                            ParameterSpec.builder("displayNamesLocale",KOTLIN_STRING_CN).defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                    break;
                default:
                    throw new IllegalArgumentException("Unsupported task: " + taskName + ".");
            }

            // Create a mutable list and add the task-specific parameters
            List<ParameterSpec.Builder> paramBuilders = new ArrayList<>(taskSpecificParamBuilders);

            // Dynamically create the ResultListener type for the current task
            ParameterizedTypeName resultListenerCn = createResultListenerTypeName(taskName, resultListenerBaseCn);
            paramBuilders.add(ParameterSpec.builder("resultListener", resultListenerCn.copy(true, Collections.emptyList())).defaultValue("null"));
            paramBuilders.add(ParameterSpec.builder("errorListener", errorListenerCn.copy(true, Collections.emptyList())).defaultValue("null"));


            // This loop now generates properties and methods for task-specific options AND listeners
            for (ParameterSpec.Builder paramBuilder : paramBuilders) {
                ParameterSpec param = paramBuilder.build();
                String paramName = param.getName();
                TypeName paramType = param.getType();

                constructorBuilder.addParameter(param);
                dataClassBuilder.addProperty(PropertySpec.builder(paramName, paramType)
                        .initializer(paramName)
                        .build());

                String methodName = "with" + paramName.substring(0, 1).toUpperCase() + paramName.substring(1);
                FunSpec withMethod = FunSpec.builder(methodName)
                        .addModifiers(KModifier.PUBLIC)
                        .returns(settingsClassName)
                        .addParameter(paramName, paramType)
                        .addStatement("return copy(%N = %N)", paramName, paramName)
                        .build();
                dataClassBuilder.addFunction(withMethod);
            }

            dataClassBuilder.primaryConstructor(constructorBuilder.build());
            classBuilder.addType(dataClassBuilder.build());
        }
    }

    private ParameterizedTypeName createResultListenerTypeName(String taskName, ClassName resultListenerBaseCn) {
        String resultTaskName = taskName;
        if (taskName.equals("InteractiveSegmenter")) {
            // InteractiveSegmenter uses ImageSegmenterResult
            resultTaskName = "ImageSegmenter";
        }
        String resultPackage = "com.google.mediapipe.tasks.vision" + "." + resultTaskName.toLowerCase();
        ClassName resultCn = new ClassName(resultPackage, resultTaskName + "Result");
        // FIX: Add the second generic type argument (MPImage) for the listener.
        ClassName mpImageCn = new ClassName("com.google.mediapipe.framework.image", "MPImage");
        return ParameterizedTypeName.get(resultListenerBaseCn, resultCn, mpImageCn);
    }

    private void generateCreators(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName futureCn,
            ClassName nonNullCn
    ) {
        for (VisionTask task : tasks) {
            String taskName = task.getName();
            if (taskName.equals("FaceStylizer")) continue;

            ClassName modelEnumCn = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Model");
            ClassName settingsRecordCn = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Settings");
            ClassName internalSettingsCn = new ClassName(PACKAGE_NAME, taskName + "SettingsInternal");
            ClassName taskReturnCn = new ClassName("com.google.mediapipe.tasks.vision." + taskName.toLowerCase(), taskName);
            ParameterizedTypeName futureOfTask = ParameterizedTypeName.get(futureCn, taskReturnCn);
            String defaultModel = task.getDefaultModel().get();

            String settingsParams = switch (taskName) {
                case "FaceDetector" -> "settings.minDetectionConfidence, settings.minSuppressionThreshold, settings.runningMode";
                case "FaceLandmarker" -> "settings.minFaceDetectionConfidence, settings.minFacePresenceConfidence, settings.minTrackingConfidence, settings.numFaces, settings.outputFaceBlendshapes, settings.outputFacialTransformationMatrixes, settings.runningMode";
                case "GestureRecognizer" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.cannedGesturesClassifierOptions, settings.customGesturesClassifierOptions, settings.runningMode";
                case "HandLandmarker" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.runningMode";
                case "ImageClassifier", "ObjectDetector" -> "settings.displayNamesLocale, settings.maxResults, settings.scoreThreshold, settings.categoryAllowlist, settings.categoryDenylist, settings.runningMode";
                case "ImageEmbedder" -> "settings.l2Normalize, settings.quantize, settings.runningMode";
                case "PoseLandmarker" -> "settings.minPoseDetectionConfidence, settings.minPosePresenceConfidence, settings.minTrackingConfidence, settings.numPoses, settings.outputSegmentationMasks, settings.runningMode";
                case "InteractiveSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.runningMode";
                case "ImageSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.displayNamesLocale, settings.runningMode";
                default -> "";
            };

            classBuilder.addFunction(
                    FunSpec.builder("create" + taskName)
                            .addAnnotation(JvmOverloads.class)
                            .addModifiers(KModifier.PUBLIC)
                            .returns(futureOfTask)
                            .addParameter(
                                    ParameterSpec.builder("model", modelEnumCn)
                                            .addAnnotation(nonNullCn)
                                            // FIX: Convert model string to uppercase to match enum constant name
                                            .defaultValue("%T.%L", modelEnumCn, defaultModel.toUpperCase())
                                            .build()
                            )
                            .addParameter(
                                    ParameterSpec.builder("settings", settingsRecordCn)
                                            .addAnnotation(nonNullCn)
                                            .defaultValue("%T()", settingsRecordCn)
                                            .build()
                            )
                            .addStatement("return create" + taskName + "Impl(model, %T(" + settingsParams + "))", internalSettingsCn)
                            .build()
            );
        }
    }
    private static final ClassName KOTLIN_STRING_CN = new ClassName("kotlin", "String");

    private void generateModels(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName visionModelCn,
            ClassName quantizationCn) {
        for (VisionTask task : tasks) {
            TypeSpec.Builder modelEnumBuilder =
                    TypeSpec.enumBuilder(task.getName() + "Model")
                            .addModifiers(KModifier.PUBLIC)
                            .addSuperinterface(visionModelCn, CodeBlock.of(""))
                            .primaryConstructor(
                                    FunSpec.constructorBuilder()
                                            .addParameter("enumName", KOTLIN_STRING_CN)
                                            .addParameter("modelName", KOTLIN_STRING_CN)
                                            .addParameter("version", KOTLIN_STRING_CN)
                                            .addParameter("quantization", quantizationCn)
                                            .build());

            // Add properties to hold the constructor values. These are not overrides themselves.
            modelEnumBuilder.addProperty(
                    PropertySpec.builder("enumName", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("enumName").build());
            modelEnumBuilder.addProperty(
                    PropertySpec.builder("modelName", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("modelName").build());
            modelEnumBuilder.addProperty(
                    PropertySpec.builder("version", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("version").build());
            modelEnumBuilder.addProperty(
                    PropertySpec.builder("quantization", quantizationCn, KModifier.OVERRIDE).initializer("quantization").build());

            task.getModels()
                    .get()
                    .forEach(
                            modelName -> {
                                VisionModel model = VisionModel.fromCanonicalName(modelName);
                                String enumConstantName = model.getEnumName();

                                // For each enum constant, create an anonymous class that overrides the interface methods.
                                TypeSpec.Builder anonymousClassBuilder =
                                        TypeSpec.anonymousClassBuilder()
                                                // Pass arguments to the enum's primary constructor
                                                .addSuperclassConstructorParameter("%S", enumConstantName)
                                                .addSuperclassConstructorParameter("%S", model.getModelName())
                                                .addSuperclassConstructorParameter("%S", model.getVersion())
                                                .addSuperclassConstructorParameter(
                                                        "%T.%L", quantizationCn, model.getQuantization());


                                modelEnumBuilder.addEnumConstant(enumConstantName, anonymousClassBuilder.build());
                            });
            classBuilder.addType(modelEnumBuilder.build());
        }
    }
}