package com.google.mediapipe.tasks.vision.provider;

import com.squareup.kotlinpoet.*;
import kotlin.jvm.JvmOverloads;
import kotlin.jvm.JvmStatic;
import org.gradle.api.NamedDomainObjectContainer;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Generates the VisionProvider.kt source file using KotlinPoet.
 */
class VisionProviderCodeGenerator {
    private static final String PACKAGE_NAME = "com.google.mediapipe.tasks.vision.provider";
    private static final ClassName KOTLIN_STRING_CN = new ClassName("kotlin", "String");
    private final NamedDomainObjectContainer<VisionTask> tasksConfiguration;

    public VisionProviderCodeGenerator(NamedDomainObjectContainer<VisionTask> tasksConfiguration) {
        this.tasksConfiguration = tasksConfiguration;
    }

    public FileSpec generateVisionProviderFile() {
        FileSpec.Builder fileBuilder = FileSpec.builder(PACKAGE_NAME, "VisionProvider");
        ClassName visionProviderClassName = new ClassName(PACKAGE_NAME, "VisionProvider");
        ClassName contextCn = new ClassName("android.content", "Context");
        ClassName futureCn = new ClassName("java.util.concurrent", "Future");
        ClassName visionModelCn = new ClassName(PACKAGE_NAME, "VisionModel");
        ClassName visionProviderBaseCn = new ClassName(PACKAGE_NAME, "VisionProviderBase");
        ClassName quantizationCn = new ClassName("com.google.mediapipe.tasks.core", "Quantization");
        ClassName runningModeCn = new ClassName("com.google.mediapipe.tasks.vision.core", "RunningMode");
        ClassName classifierOptionsCn = new ClassName("com.google.mediapipe.tasks.components.processors", "ClassifierOptions");
        ClassName nonNullCn = new ClassName("androidx.annotation", "NonNull");

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder("VisionProvider")
                .addModifiers(KModifier.PUBLIC)
                .superclass(visionProviderBaseCn)
                .addKdoc("Generated by the VisionProvider Gradle Plugin. Do not edit.");

        classBuilder.primaryConstructor(
                FunSpec.constructorBuilder()
                        .addParameter("context", contextCn)
                        .build()
        );
        classBuilder.addSuperclassConstructorParameter("context");

        TypeSpec.Builder companionBuilder = TypeSpec.companionObjectBuilder()
                .addFunction(
                        FunSpec.builder("create")
                                .addAnnotation(JvmStatic.class)
                                .addParameter(ParameterSpec.builder("context", contextCn).addAnnotation(nonNullCn).build())
                                .returns(visionProviderClassName)
                                .addStatement("return %T(context)", visionProviderClassName)
                                .build()
                );
        classBuilder.addType(companionBuilder.build());

        generateModels(classBuilder, tasksConfiguration, visionModelCn, quantizationCn);
        generateSettings(classBuilder, tasksConfiguration, runningModeCn, classifierOptionsCn);
        generateCreators(classBuilder, tasksConfiguration, futureCn, nonNullCn);

        fileBuilder.addType(classBuilder.build());
        return fileBuilder.build();
    }

    private void generateModels(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName visionModelCn,
            ClassName quantizationCn) {
        for (VisionTask task : tasks) {
            TypeSpec.Builder modelEnumBuilder =
                    TypeSpec.enumBuilder(task.name + "Model")
                            .addModifiers(KModifier.PUBLIC)
                            .addSuperinterface(visionModelCn, CodeBlock.of(""))
                            .primaryConstructor(
                                    FunSpec.constructorBuilder()
                                            .addParameter("enumName", KOTLIN_STRING_CN)
                                            .addParameter("modelName", KOTLIN_STRING_CN)
                                            .addParameter("version", KOTLIN_STRING_CN)
                                            .addParameter("quantization", quantizationCn)
                                            .build());

            modelEnumBuilder.addProperty(PropertySpec.builder("enumName", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("enumName").build());
            modelEnumBuilder.addProperty(PropertySpec.builder("modelName", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("modelName").build());
            modelEnumBuilder.addProperty(PropertySpec.builder("version", KOTLIN_STRING_CN, KModifier.OVERRIDE).initializer("version").build());
            modelEnumBuilder.addProperty(PropertySpec.builder("quantization", quantizationCn, KModifier.OVERRIDE).initializer("quantization").build());

            task.getModels()
                    .get()
                    .forEach(
                            modelName -> {
                                VisionModel model = VisionModel.fromCanonicalName(task.name, modelName);
                                String enumConstantName = model.enumName();
                                TypeSpec.Builder anonymousClassBuilder =
                                        TypeSpec.anonymousClassBuilder()
                                                .addSuperclassConstructorParameter("%S", enumConstantName)
                                                .addSuperclassConstructorParameter("%S", model.modelName())
                                                .addSuperclassConstructorParameter("%S", model.version())
                                                .addSuperclassConstructorParameter("%T.%L", quantizationCn, model.quantization());
                                modelEnumBuilder.addEnumConstant(enumConstantName, anonymousClassBuilder.build());
                            });
            classBuilder.addType(modelEnumBuilder.build());
        }
    }

    private void generateSettings(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName runningModeCn,
            ClassName classifierOptionsCn
    ) {
        ClassName visionProviderBaseCn = new ClassName(PACKAGE_NAME, "VisionProviderBase");
        ParameterizedTypeName stringListType = ParameterizedTypeName.get(new ClassName("kotlin.collections", "List"), new ClassName("kotlin", "String"));
        ClassName errorListenerCn = new ClassName("com.google.mediapipe.tasks.core", "ErrorListener");
        ClassName resultListenerBaseCn = new ClassName("com.google.mediapipe.tasks.core", "OutputHandler", "ResultListener");

        for (VisionTask task : tasks) {
            String taskName = task.name;
            if (taskName.equals("FaceStylizer")) continue;

            ClassName settingsClassName = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Settings");
            TypeSpec.Builder dataClassBuilder = TypeSpec.classBuilder(settingsClassName)
                    .addModifiers(KModifier.PUBLIC, KModifier.DATA);

            FunSpec.Builder constructorBuilder = FunSpec.constructorBuilder();
            List<ParameterSpec.Builder> taskSpecificParamBuilders = switch (taskName) {
                case "FaceDetector" -> List.of(
                        ParameterSpec.builder("minDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minSuppressionThreshold", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "FaceLandmarker" -> List.of(
                        ParameterSpec.builder("minFaceDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minFacePresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numFaces", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("outputFaceBlendshapes", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_BLENDSHAPES", visionProviderBaseCn),
                        ParameterSpec.builder("outputFacialTransformationMatrixes", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_FACIAL_TRANSFORMATION_MATRIXES", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "GestureRecognizer" -> List.of(
                        ParameterSpec.builder("minHandDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minHandPresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numHands", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("cannedGesturesClassifierOptions", classifierOptionsCn.copy(true, Collections.emptyList())).defaultValue("null"),
                        ParameterSpec.builder("customGesturesClassifierOptions", classifierOptionsCn.copy(true, Collections.emptyList())).defaultValue("null"),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "HandLandmarker" -> List.of(
                        ParameterSpec.builder("minHandDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minHandPresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numHands", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "ImageClassifier", "ObjectDetector" -> {
                    float scoreThreshold = taskName.equals("ImageClassifier") ? 0.0f : 0.5f;
                    yield List.of(
                            ParameterSpec.builder("displayNamesLocale", KOTLIN_STRING_CN).defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                            ParameterSpec.builder("maxResults", Integer.TYPE).defaultValue("%T.UNLIMITED_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("scoreThreshold", Float.TYPE).defaultValue("%Lf", scoreThreshold),
                            ParameterSpec.builder("categoryAllowlist", stringListType.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("categoryDenylist", stringListType.copy(true, Collections.emptyList())).defaultValue("null"),
                            ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    );
                }
                case "ImageEmbedder" -> List.of(
                        ParameterSpec.builder("l2Normalize", Boolean.TYPE).defaultValue("%T.DEFAULT_L2_NORMALIZE", visionProviderBaseCn),
                        ParameterSpec.builder("quantize", Boolean.TYPE).defaultValue("%T.DEFAULT_QUANTIZE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "PoseLandmarker" -> List.of(
                        ParameterSpec.builder("minPoseDetectionConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minPosePresenceConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float.TYPE).defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numPoses", Integer.TYPE).defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("outputSegmentationMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_SEGMENTATION_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "InteractiveSegmenter" -> List.of(
                        ParameterSpec.builder("outputConfidenceMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("outputCategoryMask", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                case "ImageSegmenter" -> List.of(
                        ParameterSpec.builder("outputConfidenceMasks", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("outputCategoryMask", Boolean.TYPE).defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                        ParameterSpec.builder("displayNamesLocale", KOTLIN_STRING_CN).defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn).defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                );
                default -> throw new IllegalArgumentException("Unsupported task: " + taskName + ".");
            };

            List<ParameterSpec.Builder> paramBuilders = new ArrayList<>(taskSpecificParamBuilders);
            ParameterizedTypeName resultListenerCn = createResultListenerTypeName(taskName, resultListenerBaseCn);
            paramBuilders.add(ParameterSpec.builder("resultListener", resultListenerCn.copy(true, Collections.emptyList())).defaultValue("null"));
            paramBuilders.add(ParameterSpec.builder("errorListener", errorListenerCn.copy(true, Collections.emptyList())).defaultValue("null"));

            for (ParameterSpec.Builder paramBuilder : paramBuilders) {
                ParameterSpec param = paramBuilder.build();
                constructorBuilder.addParameter(param);
                dataClassBuilder.addProperty(PropertySpec.builder(param.getName(), param.getType()).initializer(param.getName()).build());
                String methodName = "with" + param.getName().substring(0, 1).toUpperCase() + param.getName().substring(1);
                dataClassBuilder.addFunction(FunSpec.builder(methodName)
                        .addModifiers(KModifier.PUBLIC)
                        .returns(settingsClassName)
                        .addParameter(param.getName(), param.getType())
                        .addStatement("return copy(%N = %N)", param.getName(), param.getName())
                        .build());
            }

            dataClassBuilder.primaryConstructor(constructorBuilder.build());
            classBuilder.addType(dataClassBuilder.build());
        }
    }

    private ParameterizedTypeName createResultListenerTypeName(String taskName, ClassName resultListenerBaseCn) {
        String resultTaskName = taskName.equals("InteractiveSegmenter") ? "ImageSegmenter" : taskName;
        String resultPackage = "com.google.mediapipe.tasks.vision." + resultTaskName.toLowerCase();
        ClassName resultCn = new ClassName(resultPackage, resultTaskName + "Result");
        ClassName mpImageCn = new ClassName("com.google.mediapipe.framework.image", "MPImage");
        return ParameterizedTypeName.get(resultListenerBaseCn, resultCn, mpImageCn);
    }

    private void generateCreators(
            TypeSpec.Builder classBuilder,
            Iterable<VisionTask> tasks,
            ClassName futureCn,
            ClassName nonNullCn
    ) {
        for (VisionTask task : tasks) {
            String taskName = task.name;
            if (taskName.equals("FaceStylizer")) continue;

            ClassName modelEnumCn = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Model");
            ClassName settingsRecordCn = new ClassName(PACKAGE_NAME + ".VisionProvider", taskName + "Settings");
            ClassName internalSettingsCn = new ClassName(PACKAGE_NAME, taskName + "SettingsInternal");
            ClassName taskReturnCn = new ClassName("com.google.mediapipe.tasks.vision." + taskName.toLowerCase(), taskName);
            ParameterizedTypeName futureOfTask = ParameterizedTypeName.get(futureCn, taskReturnCn);
            String defaultModel = task.getDefaultModel().get();

            String settingsParams = switch (taskName) {
                case "FaceDetector" -> "settings.minDetectionConfidence, settings.minSuppressionThreshold, settings.runningMode";
                case "FaceLandmarker" -> "settings.minFaceDetectionConfidence, settings.minFacePresenceConfidence, settings.minTrackingConfidence, settings.numFaces, settings.outputFaceBlendshapes, settings.outputFacialTransformationMatrixes, settings.runningMode";
                case "GestureRecognizer" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.cannedGesturesClassifierOptions, settings.customGesturesClassifierOptions, settings.runningMode";
                case "HandLandmarker" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.runningMode";
                case "ImageClassifier", "ObjectDetector" -> "settings.displayNamesLocale, settings.maxResults, settings.scoreThreshold, settings.categoryAllowlist, settings.categoryDenylist, settings.runningMode";
                case "ImageEmbedder" -> "settings.l2Normalize, settings.quantize, settings.runningMode";
                case "PoseLandmarker" -> "settings.minPoseDetectionConfidence, settings.minPosePresenceConfidence, settings.minTrackingConfidence, settings.numPoses, settings.outputSegmentationMasks, settings.runningMode";
                case "InteractiveSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.runningMode";
                case "ImageSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.displayNamesLocale, settings.runningMode";
                default -> "";
            };

            classBuilder.addFunction(
                    FunSpec.builder("create" + taskName)
                            .addAnnotation(JvmOverloads.class)
                            .addModifiers(KModifier.PUBLIC)
                            .returns(futureOfTask)
                            .addParameter(
                                    ParameterSpec.builder("model", modelEnumCn)
                                            .addAnnotation(nonNullCn)
                                            .defaultValue("%T.%L", modelEnumCn, defaultModel.toUpperCase())
                                            .build()
                            )
                            .addParameter(
                                    ParameterSpec.builder("settings", settingsRecordCn)
                                            .addAnnotation(nonNullCn)
                                            .defaultValue("%T()", settingsRecordCn)
                                            .build()
                            )
                            .addStatement("return create" + taskName + "Impl(model, %T(" + settingsParams + "))", internalSettingsCn)
                            .build()
            );
        }
    }
}