package com.google.mediapipe.tasks.vision.provider

import com.android.build.api.dsl.ApplicationExtension
import com.android.build.api.dsl.DynamicFeatureExtension
import com.google.gson.Gson
import java.io.File
import java.io.IOException
import java.nio.file.Files
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.register// --- START: NEW IMPORTS ---
// 1. Use the 'legacy' extension that has the jniLibs property
// 2. Import the Kotlin DSL helper for extensions.getByType<T>()
import org.gradle.kotlin.dsl.getByType
// 3. Import the Kotlin DSL helper for sourceSets.named("...")
import org.gradle.kotlin.dsl.named
// --- END: NEW IMPORTS ---

class VisionProviderPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val tasksContainer = project.container(VisionTask::class.java)
        try {
            GenerateVisionProviderTask(project, tasksContainer).generate()
            // Configure asset packs, bundle settings, and automated resources
            configureProject(project)

            // --- START: MODIFIED LOGIC ---
            // This logic configures the extraction tasks for each QNN module
            // generated by AIPackModuleGenerator.

            // This list will hold all the extraction tasks we create
            val allExtractTasks = mutableListOf<org.gradle.api.provider.Provider<DefaultTask>>()

            // Get the QNN variants from the generator class
            val qnnVariants = AIPackModuleGenerator.QNN_VARIANT_MAP
            val qnnCommonFiles = AIPackModuleGenerator.QNN_COMMON_FILES

            for ((moduleName, variantFiles) in qnnVariants) {
                // Find the newly created project (e.g., :qnn_v66)
                project.rootProject.project(":$moduleName") {
                    // `this` is now the project, e.g., :qnn_v66
// Output: This module's specific jniLibs dir
                    // We define outputDir *outside* the task so we can reference it
                    val outputDir = project.rootProject.layout.buildDirectory.dir(
                        "generated/npu-modules/$moduleName/src/main/jniLibs"
                    )
                    val outputJniLibsDir = project.rootProject.layout.buildDirectory.dir(
                        "generated/npu-modules/qnn_wrapper/src/main/jniLibs"
                    )
                    // 1. Register the download/extract task for *this specific module*
                    val extractTask = tasks.register<DefaultTask>("fetchAndExtractQnnLibs") {
                        group = "build"
                        description = "Downloads QNN AAR, extracts its native libs, and creates dummy ABI folders."

                        // Input:
                        val qnnConfig = project.configurations.detachedConfiguration(
                            project.dependencies.create("com.qualcomm.qti:qnn-runtime:2.39.0@aar")
                        )
                        inputs.files(qnnConfig)

                        // Output: Point to the ROOT jniLibs directory
                        // This is correct: 'outputJniLibsDir' is a Provider<Directory>
                        outputs.dir(outputJniLibsDir)

                        // Action:
                        doLast {
                            logger.lifecycle("▶️ Running fetchAndExtractQnnLibs...")

                            // --- FIX: Get the concrete File at execution time ---
                            // Call .get() to get the Directory, then .asFile to get the java.io.File
                            val rootJniLibsFile = outputJniLibsDir.get().asFile

                            // --- Create all ABI directories using standard File operations ---
                            val abis = listOf("armeabi-v7a", "x86", "x86_64", "arm64-v8a")

                            abis.forEach { abi ->
                                // Use the File constructor
                                val abiDir = File(rootJniLibsFile, abi)
                                abiDir.mkdirs()

                                if (abi == "arm64-v8a") {
                                    logger.lifecycle("  > Preparing target dir: ${abiDir.path}")
                                } else {
                                    // Create dummy files for all other ABIs
                                    val keepFile = File(abiDir, "dummy.so")
                                    if (!keepFile.exists()) {
                                        keepFile.createNewFile()
                                        logger.lifecycle("  > Creating dummy file: ${keepFile.path}")
                                    }
                                }
                            }

                            // --- Extract the real libs ---
                            val aarFile = qnnConfig.singleFile
                            logger.lifecycle("  Downloaded ${aarFile.name}")

                            // Define the total set of files for this module
                            val filesToExtract = qnnCommonFiles + variantFiles
                            logger.lifecycle("  Targeting files: $filesToExtract")

                            project.copy {
                                includeEmptyDirs = false
                                from(project.zipTree(aarFile)) {
                                    // Filter to only the files we want for this module
                                    filesToExtract.forEach { pattern ->
                                        include("jni/arm64-v8a/$pattern")
                                    }
                                }
                                // --- START: FIX ---
                                // Get the actual File from the DirectoryProvider at execution time.
                                // This is safe inside doLast {}.
                                val outputDirAsFile = outputDir.get().asFile
                                val abiDir = File(outputDirAsFile, "arm64-v8a")
                                into(abiDir)
                                // --- END: FIX ---
                                eachFile {
                                    // Strip the "jni/arm64-v8a/" prefix
                                    val originalPath = path
                                    val newPath = originalPath.substringAfter("jni/arm64-v8a/")
                                    logger.lifecycle("  > Copying '$originalPath' -> '$newPath'")
                                    path = "./" + newPath
                                }
                            }
                            logger.lifecycle("✅ Populated all ABI folders in ${rootJniLibsFile.path}")
                        }
                    }
                    // Add this task's provider to our master list
                    allExtractTasks.add(extractTask)
                    // Defer configuration until this subproject is evaluated
                    afterEvaluate {
                        // 1. Link the source set (the "implicit" way)
                        val androidExtension = extensions.getByType<DynamicFeatureExtension>()
                        // --- START: FIX ---
                        // 3. Point jniLibs.srcDir to the *root* output dir
                        androidExtension.sourceSets {
                            named("main") {
                                jniLibs.srcDir(outputDir)
                            }
                        }
                        // --- END: FIX ---

                        // 2. Add the EXPLICIT dependency (Gradle's Solution 2)
                        // This finds tasks like 'mergeDebugJniLibFolders'
                        // within *this* module (:qnn_gpu) and makes them
                        // depend on our extraction task.
                        tasks.configureEach {
                            if (name.startsWith("merge") && name.endsWith("JniLibFolders")) {
                                logger.lifecycle("  > [:$moduleName] Hooking '$name' to depend on '${extractTask.name}'")
                                dependsOn(extractTask)
                            }
                        }
                    }
                }
            } // End of loop over modules

            // 3. Set up the dependency for the :app project
            // The :app module's JNI merge tasks must depend on *all* extraction tasks
            project.tasks.configureEach {
                // 'this' is a task in the :app project (where the plugin is applied)
                val taskName = this.name
                if (taskName == "mergeDebugJniLibFolders" ||
                    taskName == "mergeReleaseJniLibFolders" ||
                    taskName == "mergeDebugJniLibs" || // Add fallbacks
                    taskName == "mergeReleaseJniLibs") {

                    logger.lifecycle("  > [:app] Hooking '$taskName' to depend on ${allExtractTasks.size} QNN extraction tasks.")
                    // Make this merge task depend on every single extract task
                    this.dependsOn(allExtractTasks)
                }
            }

           project.logger.lifecycle("✅ Set up lazy rules to hook JNI merge tasks to all QNN extract tasks.")

            // --- END: MODIFIED LOGIC ---

        } catch (e: IOException) {
            throw RuntimeException(e)
        }
    }

    private fun configureProject(project: Project) {
        val configFile = File(project.rootDir, "tasks.json")
        if (!configFile.exists()) {
            project.logger.warn("Warning: Vision config file not found at ${configFile.path}")
            return
        }

        try {
            val androidExtension = project.extensions.findByType(ApplicationExtension::class.java)
            if (androidExtension == null) {
                project.logger.warn("Warning: Android Application plugin not found on project ${project.name}")
                return
            }

            // Get all the generated QNN module names from the map
            val qnnModuleNames = AIPackModuleGenerator.QNN_VARIANT_MAP.keys
                .map { ":$it" } // Prepend colon, e.g., ":qnn_v66"
                .toSet()

            // Add all of them to the dynamic features list
            androidExtension.dynamicFeatures.addAll(qnnModuleNames)
            project.logger.lifecycle("✅ Configured dynamic features: ${qnnModuleNames.joinToString()}")
            // --- END: MODIFIED LOGIC ---

            androidExtension.bundle {
                deviceTargetingConfig.set(
                    project.layout.buildDirectory.file("generated/res/xml/device_targeting_configuration.xml")
                )
                deviceGroup {
                    enableSplit = true
                    defaultGroup = "other"
                }
                abi {
                    enableSplit = true
                }
            }
            project.logger.lifecycle("✅ Configured Android App Bundle for device targeting.")

            val jsonContent = String(Files.readAllBytes(configFile.toPath()))
            val parsedWrapper = Gson().fromJson(jsonContent, TasksWrapper::class.java)
            val assetPackNames = parsedWrapper.tasks.values
                .flatMap { config -> config.models }
                .map { modelName -> ":aipack_$modelName" }

            if (assetPackNames.isNotEmpty()) {
                androidExtension.assetPacks.addAll(assetPackNames)
                project.logger.lifecycle("✅ Configured asset packs: ${assetPackNames.joinToString()}")
            }

        } catch (e: Exception) {
            throw RuntimeException("Failed to configure project", e)
        }
    }
}