package com.google.mediapipe.tasks.vision.provider

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import kotlin.reflect.typeOf
import org.gradle.api.NamedDomainObjectContainer

/**
 * Generates the VisionProvider.kt source file using KotlinPoet.
 */
internal class VisionProviderCodeGenerator(
        private val tasksConfiguration: NamedDomainObjectContainer<VisionTask>
) {

    companion object {
        private const val PACKAGE_NAME = "com.google.mediapipe.tasks.vision.provider"
        private val KOTLIN_STRING_CN = ClassName("kotlin", "String")
    }

    fun generateVisionProviderFile(): FileSpec {
        val fileBuilder = FileSpec.builder(PACKAGE_NAME, "VisionProvider")
        val visionProviderClassName = ClassName(PACKAGE_NAME, "VisionProvider")
        val contextCn = ClassName("android.content", "Context")
        val futureCn = ClassName("java.util.concurrent", "Future")
        val visionModelCn = ClassName(PACKAGE_NAME, "VisionModel")
        val visionTaskType = ClassName(PACKAGE_NAME, "VisionTask.Type")
        val visionProviderBaseCn = ClassName(PACKAGE_NAME, "VisionProviderBase")
        val quantizationCn = ClassName("com.google.mediapipe.tasks.core", "Quantization")
        val runningModeCn = ClassName("com.google.mediapipe.tasks.vision.core", "RunningMode")
        val classifierOptionsCn =
                ClassName("com.google.mediapipe.tasks.components.processors", "ClassifierOptions")
        val nonNullCn = ClassName("androidx.annotation", "NonNull")

        val classBuilder = TypeSpec.classBuilder("VisionProvider")
                .addModifiers(KModifier.PUBLIC)
                .superclass(visionProviderBaseCn)
                .addKdoc("Generated by the VisionProvider Gradle Plugin. Do not edit.")
                .primaryConstructor(
                        FunSpec.constructorBuilder()
                                .addParameter("context", contextCn)
                                .build()
                )
                .addSuperclassConstructorParameter("context")
                .addType(
                        TypeSpec.companionObjectBuilder()
                                .addFunction(
                                        FunSpec.builder("create")
                                                .addAnnotation(JvmStatic::class)
                            .addParameter(
                ParameterSpec.builder("context", contextCn).addAnnotation(nonNullCn).build()
        )
                .returns(visionProviderClassName)
                .addStatement("return %T(context)", visionProviderClassName)
                .build()
                    )
                    .build()
            )

        generateModels(classBuilder, tasksConfiguration, visionModelCn, quantizationCn, visionTaskType)
        generateSettings(classBuilder, tasksConfiguration, runningModeCn, classifierOptionsCn)
        generateCreators(classBuilder, tasksConfiguration, futureCn, nonNullCn)

        fileBuilder.addType(classBuilder.build())
        return fileBuilder.build()
    }

    private fun generateModels(
            classBuilder: TypeSpec.Builder,
            tasks: Iterable<VisionTask>,
            visionModelCn: ClassName,
            quantizationCn: ClassName,
            visionTaskTypeCn: ClassName
    ) {
        for (task in tasks) {
            val modelEnumBuilder =
                    TypeSpec.enumBuilder("${task.name}Model")
                            .addModifiers(KModifier.PUBLIC)
                            .addSuperinterface(visionModelCn)
                            .primaryConstructor(
                                    FunSpec.constructorBuilder()
                                            .addParameter("task", visionTaskTypeCn)
                                            .addParameter("enumName", KOTLIN_STRING_CN)
                                            .addParameter("modelName", KOTLIN_STRING_CN)
                                            .addParameter("version", KOTLIN_STRING_CN)
                                            .addParameter("quantization", quantizationCn)
                                            .build()
                            )
                            .addProperty(
                                    PropertySpec.builder("task", visionTaskTypeCn, KModifier.OVERRIDE)
                                            .initializer("task")
                                            .build()
                            )
                            .addProperty(
                                    PropertySpec.builder("enumName", KOTLIN_STRING_CN, KModifier.OVERRIDE)
                                            .initializer("enumName")
                                            .build()
                            )
                            .addProperty(
                                    PropertySpec.builder("modelName", KOTLIN_STRING_CN, KModifier.OVERRIDE)
                                            .initializer("modelName")
                                            .build()
                            )
                            .addProperty(
                                    PropertySpec.builder("version", KOTLIN_STRING_CN, KModifier.OVERRIDE)
                                            .initializer("version")
                                            .build()
                            )
                            .addProperty(
                                    PropertySpec.builder("quantization", quantizationCn, KModifier.OVERRIDE)
                                            .initializer("quantization")
                                            .build()
                            )

            val taskEnumName = task.name.replace(Regex("(?<=[a-z])(?=[A-Z])"), "_").uppercase()
            val enumConstantMember = MemberName(visionTaskTypeCn, taskEnumName)

            task.models.get().forEach { modelName ->
                    val model = VisionModel.fromCanonicalName(task.name, modelName)
                val enumConstantName = modelName
                val anonymousClassBuilder =
                        TypeSpec.anonymousClassBuilder()
                                .addSuperclassConstructorParameter(CodeBlock.of(enumConstantMember.toString()))
                                .addSuperclassConstructorParameter("%S", enumConstantName)
                                .addSuperclassConstructorParameter("%S", model.modelName())
                                .addSuperclassConstructorParameter("%S", model.version())
                                .addSuperclassConstructorParameter(
                                        "%T.%L",
                                        quantizationCn,
                                        model.quantization()
                                )
                modelEnumBuilder.addEnumConstant(modelName.uppercase(), anonymousClassBuilder.build())
            }
            classBuilder.addType(modelEnumBuilder.build())
        }
    }

    private fun generateSettings(
            classBuilder: TypeSpec.Builder,
            tasks: Iterable<VisionTask>,
            runningModeCn: ClassName,
            classifierOptionsCn: ClassName
    ) {
        val visionProviderBaseCn = ClassName(PACKAGE_NAME, "VisionProviderBase")
        val stringListType = ClassName("kotlin.collections", "List")
                .parameterizedBy(ClassName("kotlin", "String"))
        val errorListenerCn = ClassName("com.google.mediapipe.tasks.core", "ErrorListener")
        val resultListenerBaseCn =
                ClassName("com.google.mediapipe.tasks.core", "OutputHandler", "ResultListener")

        for (task in tasks) {
            val taskName = task.name
            if (taskName == "FaceStylizer") continue

            val settingsClassName = ClassName("$PACKAGE_NAME.VisionProvider", "${taskName}Settings")
            val dataClassBuilder = TypeSpec.classBuilder(settingsClassName)
                    .addModifiers(KModifier.PUBLIC, KModifier.DATA)

            val constructorBuilder = FunSpec.constructorBuilder()

            val taskSpecificParamBuilders = when (taskName) {
                "FaceDetector" -> listOf(
                        ParameterSpec.builder("minDetectionConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minSuppressionThreshold", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "FaceLandmarker" -> listOf(
                        ParameterSpec.builder("minFaceDetectionConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minFacePresenceConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numFaces", Int::class)
                        .defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("outputFaceBlendshapes", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_BLENDSHAPES", visionProviderBaseCn),
                        ParameterSpec.builder("outputFacialTransformationMatrixes", Boolean::class)
                        .defaultValue(
                        "%T.DEFAULT_OUTPUT_FACIAL_TRANSFORMATION_MATRIXES",
                        visionProviderBaseCn
                ),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "GestureRecognizer" -> listOf(
                        ParameterSpec.builder("minHandDetectionConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minHandPresenceConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numHands", Int::class)
                        .defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder(
                                        "cannedGesturesClassifierOptions",
                                        classifierOptionsCn.copy(nullable = true)
                                )
                                .defaultValue("null"),
                        ParameterSpec.builder(
                                        "customGesturesClassifierOptions",
                                        classifierOptionsCn.copy(nullable = true)
                                )
                                .defaultValue("null"),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "HandLandmarker" -> listOf(
                        ParameterSpec.builder("minHandDetectionConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minHandPresenceConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numHands", Int::class)
                        .defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "ImageClassifier", "ObjectDetector" -> {
                    val scoreThreshold = if (taskName == "ImageClassifier") 0.0f else 0.5f
                    listOf(
                            ParameterSpec.builder("displayNamesLocale", KOTLIN_STRING_CN)
                                    .defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                            ParameterSpec.builder("maxResults", Int::class)
                            .defaultValue("%T.UNLIMITED_RESULTS", visionProviderBaseCn),
                            ParameterSpec.builder("scoreThreshold", Float::class)
                            .defaultValue("%Lf", scoreThreshold),
                            ParameterSpec.builder("categoryAllowlist", stringListType.copy(nullable = true))
                                    .defaultValue("null"),
                            ParameterSpec.builder("categoryDenylist", stringListType.copy(nullable = true))
                                    .defaultValue("null"),
                            ParameterSpec.builder("runningMode", runningModeCn)
                                    .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                    )
                }

                "ImageEmbedder" -> listOf(
                        ParameterSpec.builder("l2Normalize", Boolean::class)
                        .defaultValue("%T.DEFAULT_L2_NORMALIZE", visionProviderBaseCn),
                        ParameterSpec.builder("quantize", Boolean::class)
                        .defaultValue("%T.DEFAULT_QUANTIZE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "PoseLandmarker" -> listOf(
                        ParameterSpec.builder("minPoseDetectionConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minPosePresenceConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("minTrackingConfidence", Float::class)
                        .defaultValue("%T.DEFAULT_CONFIDENCE", visionProviderBaseCn),
                        ParameterSpec.builder("numPoses", Int::class)
                        .defaultValue("%T.DEFAULT_NUM_RESULTS", visionProviderBaseCn),
                        ParameterSpec.builder("outputSegmentationMasks", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_SEGMENTATION_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "InteractiveSegmenter" -> listOf(
                        ParameterSpec.builder("outputConfidenceMasks", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("outputCategoryMask", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                "ImageSegmenter" -> listOf(
                        ParameterSpec.builder("outputConfidenceMasks", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_CONFIDENCE_MASKS", visionProviderBaseCn),
                        ParameterSpec.builder("outputCategoryMask", Boolean::class)
                        .defaultValue("%T.DEFAULT_OUTPUT_CATEGORY_MASK", visionProviderBaseCn),
                        ParameterSpec.builder("displayNamesLocale", KOTLIN_STRING_CN)
                                .defaultValue("%T.DEFAULT_DISPLAY_NAMES_LOCALE", visionProviderBaseCn),
                        ParameterSpec.builder("runningMode", runningModeCn)
                                .defaultValue("%T.DEFAULT_RUNNING_MODE", visionProviderBaseCn)
                )

                else -> throw IllegalArgumentException("Unsupported task: $taskName.")
            }

            val paramBuilders = taskSpecificParamBuilders.toMutableList()
            val resultListenerCn = createResultListenerTypeName(taskName, resultListenerBaseCn)
            paramBuilders.add(
                    ParameterSpec.builder("resultListener", resultListenerCn.copy(nullable = true))
                            .defaultValue("null")
            )
            paramBuilders.add(
                    ParameterSpec.builder("errorListener", errorListenerCn.copy(nullable = true))
                            .defaultValue("null")
            )

            for (paramBuilder in paramBuilders) {
                val param = paramBuilder.build()
                constructorBuilder.addParameter(param)
                dataClassBuilder.addProperty(
                        PropertySpec.builder(param.name, param.type).initializer(param.name).build()
                )
                val methodName = "with${param.name.replaceFirstChar { it.uppercase() }}"
                dataClassBuilder.addFunction(
                        FunSpec.builder(methodName)
                                .addModifiers(KModifier.PUBLIC)
                                .returns(settingsClassName)
                                .addParameter(param.name, param.type)
                                .addStatement("return copy(%N = %N)", param.name, param.name)
                                .build()
                )
            }

            dataClassBuilder.primaryConstructor(constructorBuilder.build())
            classBuilder.addType(dataClassBuilder.build())
        }
    }

    private fun createResultListenerTypeName(taskName: String, resultListenerBaseCn: ClassName) =
    ClassName(
            "com.google.mediapipe.framework.image",
                    "MPImage"
    ).let { mpImageCn ->
            val resultTaskName = if (taskName == "InteractiveSegmenter") "ImageSegmenter" else taskName
        val resultPackage = "com.google.mediapipe.tasks.vision.${resultTaskName.lowercase()}"
        val resultCn = ClassName(resultPackage, "${resultTaskName}Result")
        resultListenerBaseCn.parameterizedBy(resultCn, mpImageCn)
    }

    private fun generateCreators(
            classBuilder: TypeSpec.Builder,
            tasks: Iterable<VisionTask>,
            futureCn: ClassName,
            nonNullCn: ClassName
    ) {
        for (task in tasks) {
            val taskName = task.name
            if (taskName == "FaceStylizer") continue

            val modelEnumCn = ClassName("$PACKAGE_NAME.VisionProvider", "${taskName}Model")
            val settingsRecordCn = ClassName("$PACKAGE_NAME.VisionProvider", "${taskName}Settings")
            val internalSettingsCn = ClassName(PACKAGE_NAME, "${taskName}SettingsInternal")
            val taskReturnCn = ClassName("com.google.mediapipe.tasks.vision.${taskName.lowercase()}", taskName)
            val futureOfTask = futureCn.parameterizedBy(taskReturnCn)
            val defaultModel = task.defaultModel.get()

            val settingsParams = when (taskName) {
                "FaceDetector" -> "settings.minDetectionConfidence, settings.minSuppressionThreshold, settings.runningMode, settings.resultListener, settings.errorListener"
                "FaceLandmarker" -> "settings.minFaceDetectionConfidence, settings.minFacePresenceConfidence, settings.minTrackingConfidence, settings.numFaces, settings.outputFaceBlendshapes, settings.outputFacialTransformationMatrixes, settings.runningMode, settings.resultListener, settings.errorListener"
                "GestureRecognizer" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.cannedGesturesClassifierOptions, settings.customGesturesClassifierOptions, settings.runningMode, settings.resultListener, settings.errorListener"
                "HandLandmarker" -> "settings.minHandDetectionConfidence, settings.minHandPresenceConfidence, settings.minTrackingConfidence, settings.numHands, settings.runningMode, settings.resultListener, settings.errorListener"
                "ImageClassifier", "ObjectDetector" -> "settings.displayNamesLocale, settings.maxResults, settings.scoreThreshold, settings.categoryAllowlist, settings.categoryDenylist, settings.runningMode, settings.resultListener, settings.errorListener"
                "ImageEmbedder" -> "settings.l2Normalize, settings.quantize, settings.runningMode, settings.resultListener, settings.errorListener"
                "PoseLandmarker" -> "settings.minPoseDetectionConfidence, settings.minPosePresenceConfidence, settings.minTrackingConfidence, settings.numPoses, settings.outputSegmentationMasks, settings.runningMode, settings.resultListener, settings.errorListener"
                "InteractiveSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.runningMode, settings.resultListener, settings.errorListener"
                "ImageSegmenter" -> "settings.outputConfidenceMasks, settings.outputCategoryMask, settings.displayNamesLocale, settings.runningMode, settings.resultListener, settings.errorListener"
                else -> ""
            }

            classBuilder.addFunction(
                    FunSpec.builder("create$taskName")
                            .addAnnotation(JvmOverloads::class)
                    .addModifiers(KModifier.PUBLIC)
                    .returns(futureOfTask)
                    .addParameter(
                            ParameterSpec.builder("model", modelEnumCn)
                                    .addAnnotation(nonNullCn)
                                    .defaultValue("%T.%L", modelEnumCn, defaultModel.uppercase())
                                    .build()
                    )
                    .addParameter(
                            ParameterSpec.builder("settings", settingsRecordCn)
                                    .addAnnotation(nonNullCn)
                                    .defaultValue("%T()", settingsRecordCn)
                                    .build()
                    )
                    .addStatement(
                            "return create${taskName}Impl(model, %T($settingsParams))",
                            internalSettingsCn
                    )
                    .build()
            )
        }
    }
}